### ISSUE TITLE
Monetize app in AppCenter

### ISSUE THREAD

**Issue by Suzie97** [horaciodrs/TradeSim#4]
Hey, I think you should monetize the app on AppCenter even if you want to give it away for free, as it allows user to easily donate money to you.

Right now, in order to donate money, we need to download the app and then go to settings and click on donate and there are a lot of other steps that follow. 

The elementary team also recommends to monetize the app.
https://docs.elementary.io/develop/appcenter/monetizing-your-app#why-monetize

**Comment by judirraquel** [comment]
Hi, I understand but I live in Argentina and Stripe don't working here. 

I have read about Stripe will include my region between the supported countries. Until this moment I will offer TradeSim for free.

However, if exist another way to receive a payment for the TradeSim usage I am interested in this.

**Comment by Suzie97** [comment]
Oh! Is that so. Let’s hope stripe comes to Argentina soon. If you need any help with the design of TradeSim, I am more than happy to help.

**Comment by judirraquel** [comment]
Yes, I waiting that Stripe arrive to my country soon. Thank you so much for your sugerence, I will have in my consideration.
