### ISSUE TITLE
Weird AppCenter listing

### ISSUE THREAD

**Issue by Suzie97** [horaciodrs/TradeSim#5]
https://github.com/elementary/appcenter/issues/1503#issue-836648994

Hey, I guess you could update the colours for your AppCenter listing, there is very little contrast.

**Comment by judirraquel** [comment]
Hi, Yes I will change the colour. Thank you for your sugerence.

**Comment by judirraquel** [comment]
Fixed. Thanks for your comment.

**Comment by Suzie97** [comment]
You're most welcome
